DROP TABLE IF EXISTS `config`;
CREATE TABLE `config` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `key` varchar(10) DEFAULT NULL COMMENT '键',
  `value` varchar(100) DEFAULT NULL COMMENT '值',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO `config` VALUES (1, 'short_len', '6');


DROP TABLE IF EXISTS `url`;
CREATE TABLE `url` (
  `id` int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `short_url` varchar(255) DEFAULT NULL COMMENT '短链接',
  `long_url` varchar(1000) DEFAULT NULL COMMENT '长链接',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
